/** The industry a company picks from on its profile. Kept as plain strings, so it reads and sorts fine wherever it's shown. */
export const INDUSTRIES = [
  "Agriculture",
  "Automotive",
  "Banking & Finance",
  "Construction & Real Estate",
  "Consulting",
  "Consumer Goods",
  "Education",
  "Energy & Utilities",
  "Entertainment & Media",
  "Fashion & Apparel",
  "Fintech",
  "Food & Beverage",
  "Government & Public Sector",
  "Healthcare",
  "Hospitality & Tourism",
  "Insurance",
  "Legal Services",
  "Logistics & Transportation",
  "Manufacturing",
  "Marketing & Advertising",
  "Non-profit",
  "Oil & Gas",
  "Pharmaceuticals",
  "Retail & E-commerce",
  "Sports",
  "Technology",
  "Telecommunications",
  "Other",
] as const

export type Industry = (typeof INDUSTRIES)[number]
